### ISSUE TITLE
Create OpenFOAM singularity image

### ISSUE THREAD

**Issue by AndreWeiner** [nformella/Cluster-based-network-modeling-using-auto-encoders#3]
To perform simulations on TU Braunschweig's Phoenix cluster and locally on your laptop/workstation, we use [Singularity](https://sylabs.io/guides/3.6/user-guide/) containers. The advantage of containers is that you can run your software wherever you want without having to install the software or its dependencies. The only dependency is Singularity. You can follow the instructions provided in [this](https://github.com/AndreWeiner/of_pytorch_docker) repository to build a suitable container with OpenFOAM-v2006. If you like, you can modify the definition (.def) file in two ways:
- update to the newest version of OpenFOAM (v-2012); see [here](https://develop.openfoam.com/Development/openfoam/-/wikis/precompiled/debian) for Ubuntu installation instructions (the Singularity image is built based on Ubuntu 20.04)
- remove the part to install *libtorch* since we won't need the PyTorch C++ frontend

Also, add the final definition file to your repository and add instructions on how to build it to the README file.

Best, Andre

**Comment by AndreWeiner** [comment]
Hi @nformella,
have a look at the [updated repository](https://github.com/AndreWeiner/of_pytorch_docker) with OpenFOAM-v2012 and PyTorch 1.7.1.
Best, Andre

**Comment by nformella** [comment]
Hi Andre,

I figured out the memory allocation problems I had using singularity. Containers do not work with WSL1 so I had to update my Windows 10 system to a newer build in order to install WSL2. Now it is running fine. 
Trying to get GUIs to work right now via VcXsrv Windows X Server. I still have to figure out some network setting problems.

Best, Niels

**Comment by AndreWeiner** [comment]
Good to hear that you made Singularity work. If you need the X server for ParaView, it is easier to install ParaView on Windows. Regarding Visual Studio Code, you can try to access WSL via the [VScode remote plugin](https://code.visualstudio.com/blogs/2019/09/03/wsl2). These two apps should be the only ones requiring a GUI.
Best, Andre

**Comment by nformella** [comment]
Hi Andre,

I got everything up and running. However, I am not sure if by the final definition file you are referring to the Singularity.def file. I did not change anything in that file but deleted the libtorch lines in the Dockerfile.

I had some trouble building a new singularity image with the updated repository. Therefore I used WSL1 just for the image creation. In order to actually start the shell, however, I have to use WSL2. The problem seems to be related to my WSL2. I am assuming some network problem. Fortunately, there is no problem running the cylinder test case.
